version: "3"
services:
  app1:
    container_name: container1
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo

  app2:
    container_name: container2
    image: content_service/pratilipi
    ports:
      - "8000:8000"
    links:
      - mongo

  app3:
    container_name: container3
    image: user_interaction_service/pratilipi
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /database:/data/db
    ports:
      - "27017:27017"
